[workspace]
resolver = "3"
members = ["anondb", "anondb-kv", "anondb-macros"]

[workspace.dependencies]
anyhow = "1"

anondb-macros = "0"
anondb-kv = "0"

[patch.crates-io]
anondb-macros = { path = "./anondb-macros" }
anondb-kv = { path = "./anondb-kv" }
