[package]
name = "anondb"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
redb = "2.6.3"
serde = { version = "1", features = ["derive"] }
bincode = "1"
flume = "0.11.1"
anyhow = "1.0.99"
rmp = "0.8.14"
rmp-serde = "1.3.0"
blake3 = "1.8.2"
hex = "0.4.3"
serde_bytes = "0.11.17"
